[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "wolf_core"
version = "2.0.1"
description = "This is a core package for the Wolf project."
authors = ["sedelpeuch <sebastien@delpeuch.net>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pip = "22.0.0"
alabaster = "0.7.13"
attrs = "23.1.0"
babel = "2.12.1"
build = "0.10.0"
cachecontrol = "0.12.11"
certifi = "2023.5.7"
charset-normalizer = "3.1.0"
cleo = "2.0.1"
crashtest = "0.4.1"
cryptography = "40.0.2"
distlib = "0.3.6"
docutils = "0.18.1"
dulwich = "0.21.5"
filelock = "3.12.0"
html5lib = "1.1"
idna = "3.4"
imagesize = "1.4.1"
importlib-metadata = "6.6.0"
installer = "0.7.0"
jaraco-classes = "3.2.3"
jeepney = "0.8.0"
jinja2 = "3.1.2"
jsonschema = "4.17.3"
keyring = "23.13.1"
lockfile = "0.12.2"
markdown-it-py = "2.2.0"
markupsafe = "2.1.2"
mdit-py-plugins = "0.3.5"
mdurl = "0.1.2"
more-itertools = "9.1.0"
msgpack = "1.0.5"
myst-parser = "1.0.0"
packaging = "23.1"
pexpect = "4.8.0"
pkginfo = "1.9.6"
platformdirs = "3.5.1"
poetry = "1.5.0"
poetry-core = "1.6.0"
poetry-plugin-export = "1.3.1"
ptyprocess = "0.7.0"
pycparser = "2.21"
pygments = "2.15.1"
pyproject-hooks = "1.0.0"
pyrsistent = "0.19.3"
pyyaml = "6.0"
rapidfuzz = "2.15.1"
requests = "2.30.0"
requests-toolbelt = "1.0.0"
schedule = "1.2.0"
secretstorage = "3.3.3"
shellingham = "1.5.0.post1"
six = "1.16.0"
snowballstemmer = "2.2.0"
sphinx = "5.3.0"
sphinx-rtd-theme = "1.2.0"
sphinxcontrib-applehelp = "1.0.2"
sphinxcontrib-devhelp = "1.0.2"
sphinxcontrib-htmlhelp = "2.0.0"
sphinxcontrib-jquery = "4.1"
sphinxcontrib-jsmath = "1.0.1"
sphinxcontrib-qthelp = "1.0.3"
sphinxcontrib-serializinghtml = "1.1.5"
tomli = "2.0.1"
tomlkit = "0.11.8"
trove-classifiers = "2023.5.2"
urllib3 = "1.26.15"
virtualenv = "20.23.0"
webencodings = "0.5.1"
zipp = "3.15.0"
mysql-connector-python = "8.1.0"


[packages]
wolf_core = { path = "wolf_core", develop = false }