name: Publish to PyPI

on:
  release:
    types: [ created ]
  workflow_dispatch:


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate
          pip install poetry
          pip install build
          poetry install

      - name: Build Python package
        run: |
          source venv/bin/activate
          python -m build --sdist --wheel .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://pypi.org/legacy/
